spring.application.name=chapter-1-logging
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.level.root=debug
logging.level.com.chanpller=debug
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.file.name=mylog.log