spring.application.name=chapter-2-web
spring.mvc.contentnegotiation.favor-parameter=true
# thymeleaf ??
spring.thymeleaf.prefix=classpath:/templates/
# thymeleaf ??
spring.thymeleaf.suffix=.html
# thymeleaf ?? ?????????????????
spring.thymeleaf.cache=false
# thymeleaf ????
spring.thymeleaf.check-template=true
