management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=*
management.health.enabled=true
management.health.show-details=always
management.endpoint.prometheus.enabled=true
server.port=9000